import = [
  "~/.config/alacritty/themes/iterm.toml"
]
[window]
dimensions = { columns = 100, lines = 85 }
# padding = { x = 0, y = 0 }
padding = { x = 5, y = 5 }
opacity = 0.9
# blur = true


[scrolling]
# history = 0

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 15.0
glyph_offset = { x = 0, y = 0 }


[bell]
animation = "EaseOutExpo"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{key = "z", mods = "Control|Shift", action = "ToggleMaximized" },]
